### ISSUE TITLE
why I use the accuracy_test to get the results which is 50％？

### ISSUE THREAD

**Issue by exfocus** [SunskyF/EasyPR-python#2]
I use the accuracy_test of general test  in demo.py .　The results i get is only 50?

Accuracy test end!
Summary:
Total images:  203
Total time: 3832.75, Average time: 18.88
Match rate: 51.23%(104), locate rate: -22.65%
Not recognize: 
陕AE8F80.jpg
湘A05H22.jpg
皖A45277.jpg
粤AAA379.jpg
浙A50819.jpg
津MN0888.jpg
川A82M83.jpg
浙A95044.jpg
浙A21027.jpg
浙AA4586.jpg
浙A12210.jpg
苏ADW072.jpg
皖M69311.jpg
粤AL6212.jpg
浙G70000.jpg
皖Q06417.jpg
粤B901BF.jpg
浙A68952.jpg
津LS2999.jpg
浙A72220.jpg
津E28437.jpg
湘A3685C.jpg
川A019W2.jpg
川A09X20.jpg
苏E75614.jpg
湘AT8781.jpg
浙AA2270.jpg
皖Q80197.jpg
皖A09T87.jpg
粤E9R439.JPG
浙JP291Q.jpg
皖A22T43.jpg
浙AC1847.jpg
皖BBC666.jpg
浙A03168.jpg
苏EB68W9.jpg
皖Q15538.jpg
津RB7992.jpg
皖Q0686学.jpg
川AA662F.jpg
津G68991.jpg
浙AA5547.jpg
浙A12903.jpg
皖A80003.jpg
粤B2757B.jpg
津MJY929.jpg
浙A13840.jpg
浙A54614.jpg

**Comment by SunskyF** [comment]
The result in the readme belongs to EasyPR1.4.
In this repo, I just reimplment it in python (and try cnn), and I think that there are some bugs in plate_locate.
So, the result is not good.
I'm doing some work on improving it.
